# Generated by Django 4.2.8 on 2024-09-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_card_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.TextField(default='No Description'),
        ),
    ]
