# Generated by Django 4.2.8 on 2024-09-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_card_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.TextField(default='No Title'),
        ),
    ]
