# Generated by Django 4.2.8 on 2024-09-12 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_card_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='dateAdded',
            field=models.DateField(default=datetime.date(2024, 9, 12)),
        ),
    ]
