# Generated by Django 4.2.8 on 2024-09-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_card_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dateAdded',
            field=models.DateField(default='1.1.2001'),
        ),
    ]
