# Generated by Django 4.2.8 on 2024-09-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_cartmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dateAdded',
            field=models.DateField(default='2001.01.01'),
        ),
    ]
