# Generated by Django 4.2.8 on 2024-09-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_card_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dateAdded',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
