# Generated by Django 4.2.8 on 2024-09-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.TextField(default='ON SALE'),
        ),
    ]
