# Generated by Django 4.2.8 on 2024-09-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(default='No Title', max_length=200),
        ),
    ]
