# Generated by Django 4.2.8 on 2024-09-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_card_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
