# Generated by Django 4.2.8 on 2024-09-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_card_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='title',
            field=models.TextField(default='No Title'),
        ),
    ]
