# Generated by Django 4.2.8 on 2024-09-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_card_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.TextField(default='FOR SALE'),
        ),
    ]
