# Generated by Django 4.2.8 on 2024-09-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_cartmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='dateAdded',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
