# Generated by Django 5.0 on 2026-02-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_card_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
    ]
